# Generated by Django 3.1.7 on 2021-02-25 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_list_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='imdb_id',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
